import {
  BASE_URL,
  EMAIL_CALLBACK_URL,
  CONTACT_CALLBACK_URL,
  RESET_PASSWORD_CALLBACK_URL,
  STRIPE_PUBLIC_KEY,
  FLUTTERWAVE_PUBLIC_KEY,
  PAYSTACK_PUBLIC_KEY,
} from '@env';

const EnvironmentVariables = {
  BASE_URL,
  EMAIL_CALLBACK_URL,
  CONTACT_CALLBACK_URL,
  RESET_PASSWORD_CALLBACK_URL,
  STRIPE_PUBLIC_KEY,
  FLUTTERWAVE_PUBLIC_KEY,
  PAYSTACK_PUBLIC_KEY,
};

export default EnvironmentVariables;
