export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const GET_COUNTRY_DATA = 'GET_COUNTRY_DATA';
